### ISSUE TITLE
Contact to me

### ISSUE THREAD

**Issue by ProDev-Web** [IGener8/Social-Media-Platform#1]
Please discuss more detail via chatting.

As a full-stack developer, I can help you.

[Telegram] https://t.me/ProDev1205
[Skype] https://join.skype.com/invite/xAHPnMKaZkkk

**Comment by IGener8** [comment]
Hi @ProDev-Web I hope you are well.

As you can see I have a repository I built a few years ago that looks similar to a basic social network platform. I am wanting to have a developer continue finishing it to the point it can be hosted live.

The goal for this platform is to have it run similar to a subredit - instead of users being able to create sub reddit, categories will already be created for users to speak on those topics. This platform will opperate similar to a social media forum on all things seo and website development. I am also hoping to add a directory function on to it so businesses can list their services and the platform will work as a business citation as well.

**Comment by ProDev-Web** [comment]
Thank you for your kind response.
I can help you and hosting too.

**Comment by ProDev-Web** [comment]
Can you use skype or telegram?

**Comment by IGener8** [comment]
I don't use either do you use discord? You can join this channel and I will add you from there?
https://discord.gg/wMNVBfgb

We should have the hosting covered, I just need help configuring the files for the server.

**Comment by ProDev-Web** [comment]
Unfortunately, I can't use Discord.

As a professional web developer, I can help for hosting, and PHP and MySQL, Ajax this is my top skills.

If you can't use skype or telegram, we can use this article for contact.

**Comment by ProDev-Web** [comment]
and this is y Gmail address `devking1205@gmail.com`

**Comment by IGener8** [comment]
No problems, I will email you a brief overview of what I am looking for initially as well as what the plan for the experiment is.

**Comment by ProDev-Web** [comment]
Ok, I'll wait in there.
